spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/MillerGmbH
    username: root
    password: BagsBunny7
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  datasource:
#    url: ${DATASOURCE.URL}
#    username: ${DATASOURCE.USERNAME}
#    password: ${DATASOURCE.PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
        ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: always
server:
  port: 8080
#  liquibase:
#    change-log: classpath:/db/changelog/changelog-master.xml
