spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/MillerGmbH
    username: root
    password: BagsBunny7
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
